src/Controllers/ContatosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CheckPoint.Controllers
{
    public class ContatosController : Controller
    {
        private const string SESSION_EMAIL = "_EMAIL";
        private const string SESSION_USUARIO = "_USUARIO";
        [HttpGet]
        public IActionResult Index()
        {
            ViewData["User"] = HttpContext.Session.GetString(SESSION_USUARIO);
            return View();
        }
        
    }
}

src/Controllers/FaqController.cs
using Microsoft.AspNetCore.Mvc;

namespace CheckPoint.Controllers
{
    public class FaqController : Controller
    {
        private const string SESSION_EMAIL = "_EMAIL";
        private const string SESSION_USUARIO = "_USUARIO";
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Controllers/LoginController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CheckPoint.Enums;
using CheckPoint.Interfaces;
using CheckPoint.Repository;

namespace CheckPoint.Controllers
{
    public class LoginController : Controller
    {
        public const string SessionEmail = "_EMAIL";
        public const string SessionUsuario = "_USUARIO";
        
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login([FromServices] IUserService userService,IFormCollection frmLogin)
        {
            var email = frmLogin["email"];
            var password = frmLogin["senha"];

            var user = userService.GetUserBy(email, password);
            
            if (user == null)
                return RedirectToAction("RegisterUser", "User");
            
            return View();
        }

        /*[HttpPost]
        public IActionResult Login(IFormCollection frmLogin)
        {
            var email = frmLogin["email"];
            var senha = frmLogin["senha"];

            var usuario = _usuarioRepository.BuscarPor(email);

            if(usuario != null && usuario.Senha.Equals(senha))
            {
                if ( usuario.Permission.Equals(EnumPermission.ADMNISTRADOR))
                    {
                        HttpContext.Session.SetString(SessionEmail, email);
                        HttpContext.Session.SetString(SessionUsuario, usuario.Nome); 
                        
                        return RedirectToAction("Index", "Dashboard");

                    }else
                        {
                            HttpContext.Session.SetString(SessionEmail, email);
                            HttpContext.Session.SetString(SessionUsuario, usuario.Nome); 
                            
                            return RedirectToAction("RegisterComment", "Usuario");
                        }
            }   
            return RedirectToAction("RegisterUser", "Usuario");
        }*/

        public IActionResult Logout() 
        {
            HttpContext.Session.Remove(SessionEmail);
            HttpContext.Session.Remove(SessionUsuario);
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

src/Controllers/SobreController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CheckPoint.Controllers
{
    public class SobreController : Controller
    {
        private const string SESSION_EMAIL = "_EMAIL";
        private const string SESSION_USUARIO = "_USUARIO";
        [HttpGet]
        public IActionResult Index()
        {
            ViewData["User"] = HttpContext.Session.GetString(SESSION_USUARIO);
            return View();
        }
    }
}

src/Views/Shared/_DashboardLayout.cshtml
@{
        var user = (string) ViewData["User"];
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/_css/dashboard.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Ponto Digital</title>
</head>
<body>
    <main>
        <section>
                <ul class="nav nav-tabs">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Usuarios</a>
                        <div class="dropdown-menu">
                        <a class="dropdown-item" asp-controller="Dashboard" asp-action="CadastrarUsuario">Cadastrar</a>
                        <a class="dropdown-item" asp-controller="Dashboard" asp-action="ListarUsuario">Listar</a>
                        <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Dashboard" asp-action="EditarExcluirUsuario">Editar/Excluir</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Comentários</a>
                        <div class="dropdown-menu">
                        <a class="dropdown-item" asp-controller="Dashboard" asp-action="CadastrarComentario">Cadastrar</a>
                        <a class="dropdown-item" asp-controller="Dashboard" asp-action="ListarComentario">Listar</a>
                        <a class="dropdown-item" asp-controller="Dashboard" asp-action="AprovarComentario">Aprovar Comentários</a>
                        <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Dashboard" asp-action="EditarExcluirComentario">Editar/Excluir</a>
                        </div>
                    </li>
                        <div class="usuario-logado"><i class="far fa-user"></i> @user</div>
                </ul>
    </section>
        @RenderBody()
    </main>
    <!--        Fim da seção main      -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/41522ef097.js"></script>
</body>
</html>

src/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/_css/login.css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<title>Login</title>
</head>
<body>
   <section class="full-screen">
        @RenderBody()
   </section> 
</body>
</html>

src/Views/Shared/_Template.cshtml
@{
        var user = (string) ViewData["User"];
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/_css/layout.css" />
    <link rel="stylesheet" href="/_css/sobreNos.css">
    <link rel="stylesheet" href="/_css/faq.css">
    <link rel="stylesheet" href="/_css/contatos.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>Ponto Digital</title>
</head>
<body>
    <main>
        <section class="banner">
                <nav class="menu-acessibilidade">
                    <ul>
                        <li>Ir para o conteúdo</li>
                        <li>Ir para o menu</li>
                        <li>A+ A-</li>
                        <li>Contraste</li>
                    </ul>
                </nav>
                <!--        Fim do menu de acessibilidade   -->
                <div class="banner-topo content">
                    <div class="logo">
                        <img src="~/_imgs/logo-pontoDigital.png" alt="Imagem representativa do planeta terra em cor azul com uma imagem em cor amarela representando o logo do produto Ponto Digital">
                    </div>
                    <i id="menu-bar" class="fas fa-bars"></i>
                    <nav class="menu-navegacao">
                        <ul>
                            <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-controller="Sobre" asp-action="Index">Sobre nós</a></li>
                            <li><a asp-controller="Faq" asp-action="Index">Faq</a></li>
                            <li><a asp-controller="Contatos" asp-action="Index">Contatos</a></li>
                            @if (string.IsNullOrEmpty(user))
                            {
                                <li><a asp-controller="Login" asp-action="Login" class="autenticacao">Login</a></li>
                            }else
                                {
                                    <li><a asp-controller="Login" asp-action="Logout" class="autenticacao">Logout</a></li>

                                }
                            <li><a asp-controller="User" asp-action="RegisterUser" class="autenticacao">Sign in</a></li>
                        </ul>
                    </nav>
                </div>
                <!-- Fim do topo do banner com logo e menu de navegacao -->
                <div class="banner-conteudo content">
                    <div class="banner-conteudo-item-esquerdo">
                        <h1>Ponto Digital</h1>
                        <p>Gerencie a jornada de trabalho dos seus times de forma fácil e organizada.</p>
                        <button class="botao-padrao">Saiba mais</button>
                    </div>
                    <!-- Lado esquerdo de conteúdo do banner -->
                    <div class="banner-conteudo-item-direito">
                        <div class="banner-imagem-container">
                            <img src="~/_imgs/team-banner.png" alt="Desenho de uma equipe de pessoas de um escritório comemorando">
                        </div>
                    </div>
                    <!-- Lado Direito do conteúdo do banner -->
                </div>
                <div class="wave"></div>
        </section>
        <!--        Fim da seção banner-topo-->
        @RenderBody()
        <footer class="container">
                <div class="footer-box-superior">
                    <ul>
                        <li><a href="#"><span>Sobre Nós</span></a></li>
                        <li><a href="#">Missão</a></li>
                        <li><a href="#">Valores</a></li>
                        <li><a href="#">Equipe</a></li>
                    </ul>
                    <ul>
                        <li><a href="#"><span>Blog</span></a></li>
                        <li><a href="#">Tecnologia</a></li>
                        <li><a href="#">Negócios</a></li>
                    </ul>
                    <ul>
                        <li><a href="#"><span>Produto</span></a></li>
                        <li><a href="#">Vantagens</a></li>
                        <li><a href="#">Recursos</a></li>
                        <li><a href="#">Planos</a></li>
                    </ul>
                    <div class="logo-container">
                        <div class="logo-footer">
                            <img src="~/_imgs/logo-pontoDigital.png" alt="Imagem representativa do planeta terra em cor azul com uma imagem em cor amarela representando o logo do produto Ponto Digital">
                        </div>
                        <div class="logo-midias-container">
                            <div class="logo-midias">
                                <img src="~/_imgs/facebook-logo.png" alt="Icone do logo do Facebook" />
                            </div>
                            <div class=logo-midias>
                                <img src="~/_imgs/instagram-logo.png" alt="Icone do logo do Instagram" />
                            </div>
                            <div class=logo-midias>
                                <img src="~/_imgs/contato-logo.png" alt="Icone de um telefone para contato">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-box-inferior">
                    <address>Alameda Barão de Limeira, 539</address>
                    <p>Copyright © 2019 - Agora Vai</p>
                </div>
            </footer>
    </main>
    <!--        Fim da seção main      -->
</body>
</html>